#!/bin/sh
PROJECT="$HOME/projects/python/cap-project"

git add "$PROJECT/store/store"
git add "$PROJECT/store/store/*.py"
git add "$PROJECT/store/store/*.md"
git add "$PROJECT/store/store/*.rst"
git add "$PROJECT/store/tests/*.py"

git add "$PROJECT/task-server/taskserver"
git add "$PROJECT/task-server/taskserver/*.py"
git add "$PROJECT/task-server/taskserver/*.md"
git add "$PROJECT/task-server/taskserver/*.rst"
git add "$PROJECT/task-server/taskserver/tests"
git add "$PROJECT/task-server/taskserver/tests/*.py"

echo "commit message:"
read MESSAGE

git commit -m "$MESSAGE"


